name: Release Validation (Dry Run)

on:
  pull_request:
    branches:
      - <your_base_branch>  # Replace with your main branch (e.g., master, main)
    paths:
      - .github/tag_and_release/**
      - pyproject.toml
      - .github/workflows/release.yml
      - .github/workflows/release**.yml
      - .github/workflows/rw**.yaml
      - "!.github/workflows/rw_build_and_test.yaml"
      - "!.github/workflows/rw_run_all_test_and_record.yaml"
      - "!.github/workflows/rw_uv_run_test_with_multi_py_versions.yaml"
  workflow_dispatch:
    inputs:
      level:
        description: 'Release level to test'
        required: false
        default: 'auto'
        type: choice
        options:
          - auto
          - patch
          - minor
          - major

permissions:
  contents: read
  packages: read
  id-token: write  # For cosign keyless signing

concurrency:
  group: release-validate-${{ github.ref }}
  cancel-in-progress: true

env:
  # Project Configuration
  PROJECT_NAME: ${{ vars.PROJECT_NAME || github.event.repository.name }}
  BASE_BRANCH: ${{ vars.BASE_BRANCH || 'master' }}
  PACKAGE_NAME: ${{ vars.PACKAGE_NAME || github.event.repository.name }}

  # Docker Configuration
  DOCKER_HEALTH_CHECK_PORT: ${{ vars.DOCKER_HEALTH_CHECK_PORT || '8000' }}
  DOCKER_HEALTH_CHECK_PATH: ${{ vars.DOCKER_HEALTH_CHECK_PATH || '/health' }}
  DOCKER_REGISTRY_DOCKERHUB: ${{ vars.DOCKER_REGISTRY_DOCKERHUB || 'docker.io' }}
  DOCKER_REGISTRY_GHCR: ${{ vars.DOCKER_REGISTRY_GHCR || 'ghcr.io' }}

  # Application Configuration
  APP_ENV_VAR_NAME: ${{ vars.APP_ENV_VAR_NAME || 'API_TOKEN' }}
  APP_ENV_VAR_VALUE: ${{ vars.APP_ENV_VAR_VALUE || 'test_token' }}

  # Validation Configuration
  VALIDATION_VERSION: ${{ vars.VALIDATION_VERSION || '1.0.0-validation' }}
  VALIDATION_TEST_VERSION: ${{ vars.VALIDATION_TEST_VERSION || 'validation-test' }}

jobs:
  intent-parse:
    uses: Chisanan232/Template-Python-UV-Project/.github/workflows/rw_parse_release_intent.yaml@master
    with:
      level: ${{ inputs.level || 'auto' }}
      python: 'auto'
      docker: 'auto'
      docs: 'auto'
      notes: 'Validation test run'

  build_git-tag_and_create_github-release:
    uses: Chisanan232/Template-Python-UV-Project/.github/workflows/rw_build_git-tag_and_create_github-release_v2.yaml@master
    needs: intent-parse
    with:
      version: ${{ env.VALIDATION_VERSION }}  # Test version for validation
      debug_mode: true
    secrets:
      github_auth_token: ${{ secrets.GITHUB_TOKEN }}

  python-build-check:
    uses: ./.github/workflows/rw_python_package.yaml
    needs: build_git-tag_and_create_github-release
    with:
      operation: 'test'
      artifact-name: 'validation-python-package'

  docker-build-dockerhub:
    name: Validate DockerHub Build
    uses: Chisanan232/Template-Python-UV-Project/.github/workflows/rw_docker_operations.yaml@master
    needs: build_git-tag_and_create_github-release
    with:
      operation: 'test'
      registry: ${{ env.DOCKER_REGISTRY_DOCKERHUB }}
      image-name: ${{ github.repository }}
      version: ${{ env.VALIDATION_TEST_VERSION }}
      health-check-port: ${{ env.DOCKER_HEALTH_CHECK_PORT }}
      health-check-path: ${{ env.DOCKER_HEALTH_CHECK_PATH }}
      enable-signing: true
      app-env-var-name: ${{ env.APP_ENV_VAR_NAME }}
      app-env-var-value: ${{ env.APP_ENV_VAR_VALUE }}

  docker-build-ghcr:
    name: Validate GHCR Build
    uses: Chisanan232/Template-Python-UV-Project/.github/workflows/rw_docker_operations.yaml@master
    needs: build_git-tag_and_create_github-release
    with:
      operation: 'test'
      registry: ${{ env.DOCKER_REGISTRY_GHCR }}
      image-name: ${{ github.repository }}
      version: ${{ env.VALIDATION_TEST_VERSION }}
      health-check-port: ${{ env.DOCKER_HEALTH_CHECK_PORT }}
      health-check-path: ${{ env.DOCKER_HEALTH_CHECK_PATH }}
      enable-signing: true
      app-env-var-name: ${{ env.APP_ENV_VAR_NAME }}
      app-env-var-value: ${{ env.APP_ENV_VAR_VALUE }}

  docs-build:
    uses: Chisanan232/Template-Python-UV-Project/.github/workflows/rw_docs_operations.yaml@master
    needs: intent-parse
    with:
      operation: 'test'
      upload-artifacts: true

  supply-chain-loopback:
    name: Security Scan (Supply Chain)
    uses: Chisanan232/Template-Python-UV-Project/.github/workflows/rw_docker_operations.yaml@master
    needs: [docker-build-dockerhub, docker-build-ghcr]
    with:
      operation: 'security-scan'
      registry: ${{ env.DOCKER_REGISTRY_DOCKERHUB }}  # Use DockerHub build for security scan
      image-name: ${{ github.repository }}
      version: ${{ env.VALIDATION_TEST_VERSION }}
      enable-sbom: true
      enable-signing: true
      app-env-var-name: ${{ env.APP_ENV_VAR_NAME }}
      app-env-var-value: ${{ env.APP_ENV_VAR_VALUE }}

  validation-summary:
    name: Validation Summary
    runs-on: ubuntu-latest
    needs: [intent-parse, python-build-check, docker-build-dockerhub, docker-build-ghcr, docs-build, supply-chain-loopback]
    if: always()
    steps:
      - name: Check validation results
        run: |
          echo "=== Release Validation Summary ==="
          echo ""
          echo "Intent Parsing: ${{ needs.intent-parse.result }}"
          echo "Python Build: ${{ needs.python-build-check.result }}"
          echo "DockerHub Build: ${{ needs.docker-build-dockerhub.result }}"
          echo "GHCR Build: ${{ needs.docker-build-ghcr.result }}"
          echo "Docs Build: ${{ needs.docs-build.result }}"
          echo "Supply Chain: ${{ needs.supply-chain-loopback.result }}"
          echo ""
          
          if [[ "${{ needs.intent-parse.result }}" == "success" && \
                "${{ needs.python-build-check.result }}" == "success" && \
                "${{ needs.docker-build-dockerhub.result }}" == "success" && \
                "${{ needs.docker-build-ghcr.result }}" == "success" && \
                "${{ needs.docs-build.result }}" == "success" && \
                "${{ needs.supply-chain-loopback.result }}" == "success" ]]; then
            echo "✅ All validation checks passed! Release process is ready."
            echo ""
            echo "Release Configuration:"
            echo "- Do Release: ${{ needs.intent-parse.outputs.do_release }}"
            echo "- Level: ${{ needs.intent-parse.outputs.level }}"
            echo "- Python: ${{ needs.intent-parse.outputs.python }}"
            echo "- Docker: ${{ needs.intent-parse.outputs.docker }}"
            echo "- Docs: ${{ needs.intent-parse.outputs.docs }}"
            echo "- Notes: ${{ needs.intent-parse.outputs.notes }}"
          else
            echo "❌ Some validation checks failed. Please review the logs above."
            exit 1
          fi
